import re


class YTConsts:
    ignore_tags = {
        "#stayhome",
        "#withme",
        "10 min",
        "10 minute",
        "10min",
        "11 minute ab workout",
        "14 day",
        "2 week",
        "2 week workout program",
        "20",
        "20 min",
        "20min",
        "30 min",
        "30 minute",
        "30min",
        "30min hiit",
        "40 min",
        "40min",
        "45 minute",
        "60 minute",
        "60 minute workout with dumbbells",
        "abnehmen",
        "activation",
        "aero",
        "air fit",
        "and",
        "apartment",
        "arm slimming",
        "arm toning without weights",
        "athletes",
        "back fat workout",
        "bat wings workout",
        "be more flexible",
        "body",
        "bodyweight booty workout",
        "bootcamp",
        "bootcamp workout",
        "build a butt",
        "build lean muscle",
        "build muscle and burn fat",
        "build strength workout",
        "burn fat",
        "but",
        "calorie killer",
        "challenge",
        "chizzled back",
        "chizzled chest",
        "class",
        "conditioning",
        "condo workout",
        "corona workout",
        "day",
        "day 3",
        "day stretching",
        "diät",
        "dumbbell  for",
        "fat",
        "fat burning",
        "fett verbrennen",
        "fit",
        "fitness",
        "fitness challenge",
        "flat abs",
        "for",
        "for relaxation",
        "for sore muscles",
        "for women",
        "free workout program",
        "free workouts",
        "friendly",
        "from home",
        "full",
        "full length hiit workout",
        "full length workout",
        "full length workout video",
        "get abs",
        "get fit from home",
        "get lean workout",
        "get shredded",
        "get stronger",
        "get toned",
        "get toned arms",
        "heather robertson fierce",
        "heather robinson",
        "heatherrobertson fierce",
        "high",
        "hit",
        "hitt",
        "home",
        "home workout",
        "how to glow up",
        "hr12week 2.0 day 8",
        "improve flexibility",
        "increase metabolism",
        "ing",
        "inner and outer thigh slimming workout",
        "intense",
        "intense workout",
        "intensity",
        "joga",
        "joga ore",
        "jogo",
        "jogos",
        "jogos juosta",
        "jogos pamoka",
        "juice and toya stretch",
        "lean and strong",
        "leg slimming workout",
        "lesson",
        "living room workout",
        "long and lean",
        "long lean body workout",
        "lose",
        "lower body  no weights",
        "madfit apartment friendly",
        "men",
        "metabolism boosting",
        "muscle",
        "new year challenge weight loss",
        "no gym workout",
        "no gym workout at home",
        "no repeet",
        "no repeets",
        "no talking",
        "no talking workout",
        "noise",
        "ore",
        "oro",
        "oro joga",
        "oro jogos juosta",
        "oro jogos pamoka",
        "quarantine workout",
        "quick daily workout",
        "quick workout",
        "quiet",
        "pose",
        "real time workout",
        "relaxing",
        "rest",
        "rest days for muscle growth",
        "round booty",
        "rounder butt",
        "routine",
        "routines",
        "schlank werden",
        "series",
        "sholder",
        "six pack workout",
        "slim arms",
        "slim legs workout",
        "slimming",
        "sore muscles",
        "stay home workout",
        "tabata for beginners",
        "teach",
        "teacher",
        "thin arms",
        "thin legs workout",
        "thinner",
        "thinner legs workout",
        "tight hips",
        "tighten skin workout",
        "tiny waist round butt",
        "tutorial",
        "weight loss workout",
        "with",
        "with me",
        "wod",
        "wokrout",
        "women",
        "workout at home",
        "workout for 10 minutes",
        "workout for 10 minutes a day",
        "workout for building strength",
        "workout for legs",
        "workout for people who get bored",
        "workout for weight loss",
        "workout from anywhere",
        "workout from home",
        "workout of the day",
        "workout video",
        "workouts for weight loss",
        "workouts for women",
    }

    strip_words = {
        " for strength",
        "10 min",
        "10 minute",
        "20 min",
        "20 minute",
        "30 min",
        "30 minute",
        "11 line",
        "at home",
        "best",
        "bootcamp",
        "brutal",
        "build a",
        "burn",
        "circuit",
        "class",
        "exercise",
        "exercises",
        "exercises for",
        "fat burning",
        "fitness",
        "flat",
        "follow along",
        "for women",
        "from home",
        "heather robinson",
        "hitt",
        "home workout with",
        "lean",
        "lesson",
        "only",
        "post",
        "practice",
        "program",
        "quick",
        "sculpted",
        "sculpting",
        "shred",
        "strenth",
        "strong",
        "tighh",
        "tight",
        "tighten",
        "toned",
        "toning",
        "training",
        "tutorial",
        "workout",
        "workout a day",
        "workout challenge",
        "workout program",
        "workouts",
        "wrkout",
    }

    possible_tags = {
        "abs",
        "arms",
        "biceps",
        "booty",
        "cardio",
        "chest",
        "core",
        "delts",
        "dumbbells",
        "full body",
        "glutes",
        "hiit",
        "legs",
        "low impact",
        "lower body",
        "mini-band",
        "no equipment",
        "no jumping",
        "shoulders",
        "strength",
        "tabata",
        "total body",
        "triceps",
        "upper body",
        "weights",
    }

    expands = {
        "abs and booty": {"butt", "abs"},
        "arm and ab": {"arms", "abs"},
        "arms and abs": {"arms", "abs"},
        "chest and back": {"chest", "back"},
        "chest triceps and shoulder": {"chest", "shoulder", "triceps"},
        "dumbbell supersets": {"weights", "supersets"},
        "full body hiit": {"hiit", "full body"},
        "full body stretch": {"stretching", "full body"},
        "legs and glutes": {"glutes", "legs"},
        "low impact cardio": {"cardio", "low impact"},
        "no repeat   weights": {"no repeats", "weights"},
        "no repeat hiit": {"hiit", "no repeats"},
        "pilates hiit": {"hiit", "pilates"},
        "strength with dumbells": {"strength", "weights"},
        "strength and cardio": {"strength", "cardio"},
        "tabata cardio": {"tabata", "cardio"},
        "total body   dumbbells": {"weights", "full body"},
        "total body dumbbell": {"weights", "full body"},
        "total body hiit": {"hiit", "full body"},
        "total body strength": {"strength", "full body"},
        "upper body strength": {"strength", "upper body"},
        "upper body superset": {"upper body", "supersets"},
    }

    dedupes = {
        "10 minute total body workout": "full body",
        "10 min full body": "full body",
        "20 min apartment": "no jumping",
        "20 min full body": "full body",
        "30 minute cardio": "cardio",
        "40s work +20s rest": "40s work + 20s rest",
        "ab": "abs",
        "active rest": "active recovery",
        "active rest day": "active recovery",
        "active stretch": "active stretching",
        "aerialpractice": "aerial",
        "air": "aerial",
        "antigravity": "aerial",
        "apartment friendly": "no jumping",
        "arm": "arms",
        "band": "mini-band",
        "bicep": "biceps",
        "body weight": "no equipment",
        "body-weight": "no equipment",
        "body-weighted": "no equipment",
        "bodyweight": "no equipment",
        "bootie": "butt",
        "booty": "butt",
        "booty  with band": "mini-band",
        "bum": "butt",
        "compound": "metcon",
        "dumbbell": "weights",
        "dumbbells": "weights",
        "dumbell": "weights",
        "dumbells": "weights",
        "entire body": "full body",
        "flute": "butt",
        "for entire body": "full body",
        "for people who get bored": "no repeats",
        "glow up challenge": "glow up",
        "glute": "glutes",
        "glutes": "butt",
        "guided stretch": "stretching",
        "hammock": "aerial hammock",
        "hammock conditioning": "aerial",
        "hip stretches": "hip stretch",
        "hips stretch": "hip stretch",
        "juice and toya": "juice & toya",
        "knee safe": "knee friendly",
        "leg": "legs",
        "leg day": "legs",
        "metabolic": "metcon",
        "metabolic conditioning": "metcon",
        "metcan": "metcon",
        "mini band": "mini-band",
        "no dumbbells": "no equipment",
        "no equiment": "no equipment",
        "no repeat": "no repeats",
        "no repetitive": "no repeats",
        "no squats no lunges": "knee friendly",
        "no weight": "no equipment",
        "no weights": "no equipment",
        "no weights glute": "no equipment",
        "non repetative": "no repeats",
        "non repetitive": "no repeats",
        "post  stretch": "stretching",
        "recovery stretch": "stretching",
        "sling": "aerial hammock",
        "sholders": "shoulders",
        "shoulders": "shoulder",
        "stregnth": "strength",
        "strenght": "strength",
        "strenth": "strength",
        "stretch": "stretching",
        "stretch for hips": "hip stretch",
        "stretch for relaxation": "stretching",
        "stretch for sore muscles": "stretching",
        "stretches": "stretching",
        "stretches for hips": "hip stretch",
        "stretching routine": "stretching",
        "super set": "supersets",
        "super sets": "supersets",
        "superset": "supersets",
        "swing": "aerial hammock",
        "tabatta": "tabata",
        "tabbata": "tabata",
        "that doesn't repeat": "no repeats",
        "total body": "full body",
        "tricep": "triceps",
        "uper body": "upper body",
        "upsidedown": "inversion",
        "vinyasa flow": "vinyasa",
        "weight": "weights",
        "without equipment": "no equipment",
        "without weights": "no equipment",
    }

    mappings = {
        "triceps": "upper body",
        "biceps": "upper body",
        "delts": "upper body",
        "back": "upper body",
        "chest": "upper body",
        "shoulder": "upper body",
        "arms": "upper body",
        "abs": "core",
        "glutes": "butt",
        "legs": "lower body",
        "quads": "lower body",
        "hamstrings": "lower body",
        "thighs": "lower body",
    }

    exercise_plurals = {
        "push up",
        "raise",
        "fly",
        "row",
        "extension",
        "back",
        "sit",
        "swimmer",
        "kickback",
        "swing",
        "deadlift",
        "pull over",
        "jack",
        "lunge",
        "pump",
        "climber",
        "drop",
        "leg lift",
        "squat",
        "hop",
        "skull crusher",
        "speed skater",
        "swimmer",
        "burpee",
        "curl",
        "drop",
        "bridge pulse",
        "sprint",
        "plank tap",
    }

    exercises_strip = {
        "cardio burst:",
    }

    exercise_dupes = {
        "kick back": "kickbacks",
        "kick backs": "kickbacks",
        "burn out": "burnout",
        "hi-low swing": "hi-lo swing",
        "knee drives": "knee driver",
        "knee drive": "knee driver",
        "lay down": "laydown",
        "100's": "100",
        "kick thru": "kick-thru",
        "sit up": "sit-up",
        "wood chop": "wood chopper",
        "woodchopper": "wood chopper",
        "l raises": "l-raises",
        "v lift": "v-lift",
        "burpees clap": "burpees + clap",
        "curls press + twist": "curls, press + twist",
        "curtsey lunges": "curtsey",
        "negative curls": "negative bicep curls",
        "scissor squats hops": "scissor squats + hops",
        "squat curl + hop": "squats, curls + hops",
        "squat curl + press": "squats, curls + press",
    }

    id_regex = re.compile(
        "^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/|shorts\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*"
    )

    chapters_regex = re.compile("(\d{0,2}:?\d{1,2}:\d{2})(.+)")
