# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.date_range import DateRange
from swagger_server.models.equipment import Equipment
from swagger_server.models.hr_range import HRRange
from swagger_server.models.hr_zone_above import HRZoneAbove
from swagger_server.models.hr_zone_range import HRZoneRange
from swagger_server import util


class WorkoutQueryParams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, date_range: DateRange=None, sport: List[str]=None, samples: bool=None, equipment: List[Equipment]=None, hr_range: HRRange=None, avg_hr_range: HRRange=None, in_hr_zone: List[HRZoneRange]=None, above_hr_zone: List[HRZoneAbove]=None):  # noqa: E501
        """WorkoutQueryParams - a model defined in Swagger

        :param date_range: The date_range of this WorkoutQueryParams.  # noqa: E501
        :type date_range: DateRange
        :param sport: The sport of this WorkoutQueryParams.  # noqa: E501
        :type sport: List[str]
        :param samples: The samples of this WorkoutQueryParams.  # noqa: E501
        :type samples: bool
        :param equipment: The equipment of this WorkoutQueryParams.  # noqa: E501
        :type equipment: List[Equipment]
        :param hr_range: The hr_range of this WorkoutQueryParams.  # noqa: E501
        :type hr_range: HRRange
        :param avg_hr_range: The avg_hr_range of this WorkoutQueryParams.  # noqa: E501
        :type avg_hr_range: HRRange
        :param in_hr_zone: The in_hr_zone of this WorkoutQueryParams.  # noqa: E501
        :type in_hr_zone: List[HRZoneRange]
        :param above_hr_zone: The above_hr_zone of this WorkoutQueryParams.  # noqa: E501
        :type above_hr_zone: List[HRZoneAbove]
        """
        self.swagger_types = {
            'date_range': DateRange,
            'sport': List[str],
            'samples': bool,
            'equipment': List[Equipment],
            'hr_range': HRRange,
            'avg_hr_range': HRRange,
            'in_hr_zone': List[HRZoneRange],
            'above_hr_zone': List[HRZoneAbove]
        }

        self.attribute_map = {
            'date_range': 'dateRange',
            'sport': 'sport',
            'samples': 'samples',
            'equipment': 'equipment',
            'hr_range': 'hrRange',
            'avg_hr_range': 'avgHRRange',
            'in_hr_zone': 'inHRZone',
            'above_hr_zone': 'aboveHRZone'
        }

        self._date_range = date_range
        self._sport = sport
        self._samples = samples
        self._equipment = equipment
        self._hr_range = hr_range
        self._avg_hr_range = avg_hr_range
        self._in_hr_zone = in_hr_zone
        self._above_hr_zone = above_hr_zone

    @classmethod
    def from_dict(cls, dikt) -> 'WorkoutQueryParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkoutQueryParams of this WorkoutQueryParams.  # noqa: E501
        :rtype: WorkoutQueryParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def date_range(self) -> DateRange:
        """Gets the date_range of this WorkoutQueryParams.


        :return: The date_range of this WorkoutQueryParams.
        :rtype: DateRange
        """
        return self._date_range

    @date_range.setter
    def date_range(self, date_range: DateRange):
        """Sets the date_range of this WorkoutQueryParams.


        :param date_range: The date_range of this WorkoutQueryParams.
        :type date_range: DateRange
        """

        self._date_range = date_range

    @property
    def sport(self) -> List[str]:
        """Gets the sport of this WorkoutQueryParams.

        Filter by sport type. Sports are ORed  # noqa: E501

        :return: The sport of this WorkoutQueryParams.
        :rtype: List[str]
        """
        return self._sport

    @sport.setter
    def sport(self, sport: List[str]):
        """Sets the sport of this WorkoutQueryParams.

        Filter by sport type. Sports are ORed  # noqa: E501

        :param sport: The sport of this WorkoutQueryParams.
        :type sport: List[str]
        """

        self._sport = sport

    @property
    def samples(self) -> bool:
        """Gets the samples of this WorkoutQueryParams.

        Whether to include samples in return  # noqa: E501

        :return: The samples of this WorkoutQueryParams.
        :rtype: bool
        """
        return self._samples

    @samples.setter
    def samples(self, samples: bool):
        """Sets the samples of this WorkoutQueryParams.

        Whether to include samples in return  # noqa: E501

        :param samples: The samples of this WorkoutQueryParams.
        :type samples: bool
        """

        self._samples = samples

    @property
    def equipment(self) -> List[Equipment]:
        """Gets the equipment of this WorkoutQueryParams.

        Filter by equipment used in the workout.  It is possible to leave off magnitude or quantity, but equipmentType must always be specified   # noqa: E501

        :return: The equipment of this WorkoutQueryParams.
        :rtype: List[Equipment]
        """
        return self._equipment

    @equipment.setter
    def equipment(self, equipment: List[Equipment]):
        """Sets the equipment of this WorkoutQueryParams.

        Filter by equipment used in the workout.  It is possible to leave off magnitude or quantity, but equipmentType must always be specified   # noqa: E501

        :param equipment: The equipment of this WorkoutQueryParams.
        :type equipment: List[Equipment]
        """

        self._equipment = equipment

    @property
    def hr_range(self) -> HRRange:
        """Gets the hr_range of this WorkoutQueryParams.


        :return: The hr_range of this WorkoutQueryParams.
        :rtype: HRRange
        """
        return self._hr_range

    @hr_range.setter
    def hr_range(self, hr_range: HRRange):
        """Sets the hr_range of this WorkoutQueryParams.


        :param hr_range: The hr_range of this WorkoutQueryParams.
        :type hr_range: HRRange
        """

        self._hr_range = hr_range

    @property
    def avg_hr_range(self) -> HRRange:
        """Gets the avg_hr_range of this WorkoutQueryParams.


        :return: The avg_hr_range of this WorkoutQueryParams.
        :rtype: HRRange
        """
        return self._avg_hr_range

    @avg_hr_range.setter
    def avg_hr_range(self, avg_hr_range: HRRange):
        """Sets the avg_hr_range of this WorkoutQueryParams.


        :param avg_hr_range: The avg_hr_range of this WorkoutQueryParams.
        :type avg_hr_range: HRRange
        """

        self._avg_hr_range = avg_hr_range

    @property
    def in_hr_zone(self) -> List[HRZoneRange]:
        """Gets the in_hr_zone of this WorkoutQueryParams.

        Time spent within a specific heart rate zone  # noqa: E501

        :return: The in_hr_zone of this WorkoutQueryParams.
        :rtype: List[HRZoneRange]
        """
        return self._in_hr_zone

    @in_hr_zone.setter
    def in_hr_zone(self, in_hr_zone: List[HRZoneRange]):
        """Sets the in_hr_zone of this WorkoutQueryParams.

        Time spent within a specific heart rate zone  # noqa: E501

        :param in_hr_zone: The in_hr_zone of this WorkoutQueryParams.
        :type in_hr_zone: List[HRZoneRange]
        """

        self._in_hr_zone = in_hr_zone

    @property
    def above_hr_zone(self) -> List[HRZoneAbove]:
        """Gets the above_hr_zone of this WorkoutQueryParams.

        Time spent above a specific heart rate zone  # noqa: E501

        :return: The above_hr_zone of this WorkoutQueryParams.
        :rtype: List[HRZoneAbove]
        """
        return self._above_hr_zone

    @above_hr_zone.setter
    def above_hr_zone(self, above_hr_zone: List[HRZoneAbove]):
        """Sets the above_hr_zone of this WorkoutQueryParams.

        Time spent above a specific heart rate zone  # noqa: E501

        :param above_hr_zone: The above_hr_zone of this WorkoutQueryParams.
        :type above_hr_zone: List[HRZoneAbove]
        """

        self._above_hr_zone = above_hr_zone
