# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ZoneType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BELOW_50 = "below_50"
    FIFTY_TO_60 = "fifty_to_60"
    SIXTY_TO_70 = "sixty_to_70"
    SEVENTY_TO_80 = "seventy_to_80"
    EIGHTY_TO_90 = "eighty_to_90"
    NINETY_TO_100 = "ninety_to_100"

    def __init__(self):  # noqa: E501
        """ZoneType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ZoneType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ZoneType of this ZoneType.  # noqa: E501
        :rtype: ZoneType
        """
        return util.deserialize_model(dikt, cls)
