---
swagger: "2.0"
info:
  description: API to access workout data
  version: 1.0.0
  title: Workout API
host: virtserver.swaggerhub.com
basePath: /api
tags:
- name: workout
  description: Info around a specific workout
- name: source
  description: What workout is done
schemes:
- https
- http
definitions:
  Everything:
    type: object
    properties:
      sources:
        type: array
        items:
          $ref: '#/definitions/Source'
      workouts:
        type: array
        items:
          $ref: '#/definitions/Workout'
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      equipment:
        type: array
        items:
          $ref: '#/definitions/Equipment'
  Tag:
    type: object
    required:
    - id
    - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tagType:
        $ref: '#/definitions/TagType'
  Equipment:
    type: object
    required:
    - equipmentType
    properties:
      id:
        type: integer
        format: int64
      equipmentType:
        $ref: '#/definitions/EquipmentType'
      magnitude:
        type: string
        example: 5lbs
        description: The weight or strength of the equipment
      quantity:
        type: integer
        description: Only relvant for weights, e.g. used 1 or 2 dumbbells
  Source:
    type: object
    required:
    - id
    - url
    properties:
      id:
        type: integer
        format: int64
      url:
        type: string
        description: The descriptive and unique identifier for the source - may not actually be a web address
      name:
        type: string
      creator:
        type: string
      duration:
        type: string
        example: P1DT12H
        description: Duration in ISO 8601 format
      sourceType:
        $ref: '#/definitions/SourceType'
      extraInfo:
        type: string
        description: Field that could be used to add sourceType specific info
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      tagIds:
        type: array
        items:
          type: integer
  HRZone:
    type: object
    required:
    - id
    - zoneType
    properties:
      id:
        type: integer
        format: int64
      zoneType:
        $ref: '#/definitions/ZoneType'
      lowerLimit:
        type: integer
      upperLimit:
        type: integer
      duration:
        type: string
        example: P1DT12H
        description: Duration in ISO 8601 format
      percentSpentAbove:
        type: number
        format: float
        description: Convenience value to describe the total percentage of the workout spent in this zone or higher
  Workout:
    type: object
    required:
    - id
    - startTime
    properties:
      id:
        type: integer
        format: int64
      startTime:
        type: string
        format: date-time
        example: 2022-12-10T00:14:25-00:00
      endTime:
        type: string
        format: date-time
        example: 2022-12-10T00:14:25-00:00
      samples:
        type: array
        items:
          type: integer
      sport:
        type: string
      calories:
        type: integer
      avgHR:
        type: integer
      minHR:
        type: integer
      maxHR:
        type: integer
      notes:
        type: string
      equipment:
        type: array
        items:
          $ref: '#/definitions/Equipment'
      equipmentIds:
        type: array
        items:
          type: integer
      sources:
        type: array
        items:
          $ref: '#/definitions/Source'
      sourceIds:
        type: array
        items:
          type: integer
      tags:
        type: array
        items:
          $ref: '#/definitions/Tag'
      tagIds:
        type: array
        items:
          type: integer
      hrZones:
        type: array
        items:
          $ref: '#/definitions/HRZone'
  SourceQuery:
    type: object
    properties:
      query:
        $ref: '#/definitions/Query'
    description: Convenience wrapper around Query to specifically return Source objects
  WorkoutQuery:
    type: object
    properties:
      query:
        $ref: '#/definitions/Query'
    description: Convenience wrapper around Query to specifically return Workout objects
  Query:
    type: object
    properties:
      sourceAttributes:
        $ref: '#/definitions/SourceQueryParams'
      workoutAttributes:
        $ref: '#/definitions/WorkoutQueryParams'
      tags:
        type: array
        items:
          type: string
      tagTypes:
        type: array
        items:
          $ref: '#/definitions/TagType'
      paginate:
        type: boolean
    description: Allow searching for resources using a wide range of parameters
  SourceQueryParams:
    type: object
    properties:
      creator:
        type: array
        description: Filter by source creator
        items:
          type: string
      exercises:
        type: array
        description: Return workouts which used a source containing this exercise
        items:
          type: string
      lengthMin:
        type: integer
        description: Minimum length of a source
      lengthMax:
        type: integer
        description: Maximum length of a source
      sourceType:
        type: array
        items:
          $ref: '#/definitions/SourceType'
  WorkoutQueryParams:
    type: object
    properties:
      tags:
        type: array
        description: Tags to filter by
        items:
          type: string
      tagTypes:
        type: array
        description: Filter by specific type of tag
        items:
          type: string
      dateRange:
        $ref: '#/definitions/DateRange'
      sport:
        type: array
        description: Filter by sport type
        items:
          type: string
      samples:
        type: boolean
        description: Whether to include samples in return
      equipment:
        type: array
        description: "Filter by equipment used in the workout. \nIt is possible to leave off magnitude or quantity, but equipmentType must always be specified\n"
        items:
          $ref: '#/definitions/Equipment'
      hrRange:
        $ref: '#/definitions/HRRange'
      avgHRRange:
        $ref: '#/definitions/HRRange'
      inHRZone:
        type: array
        description: Time spent within a specific heart rate zone
        items:
          $ref: '#/definitions/HRZoneRange'
      aboveHRZone:
        type: array
        description: Time spent within and above a specific heart rate zone
        items:
          $ref: '#/definitions/HRZoneRange'
      sourceParams:
        $ref: '#/definitions/SourceQueryParams'
  DateRange:
    type: object
    properties:
      start:
        type: string
        format: date-time
      end:
        type: string
        format: date-time
    description: Get workouts within a range. Either start or end can be omitted.
  HRRange:
    type: object
    properties:
      min:
        type: integer
      max:
        type: integer
    description: Range for heart rate values. Either min or max can be omitted.
  HRZoneRange:
    type: object
    properties:
      zoneType:
        $ref: '#/definitions/ZoneType'
      minTime:
        type: string
        example: P1DT12H
        description: Duration in ISO 8601 format
      maxTime:
        type: string
        example: P1DT12H
        description: Duration in ISO 8601 format
    description: Time range spent in this HR zone. Either min or max can be omitted.
  ZoneType:
    type: string
    description: The range (percentile relative to max HR) this zone covers
    enum:
    - below_50
    - fifty_to_60
    - sixty_to_70
    - seventy_to_80
    - eighty_to_90
    - ninety_to_100
  TagType:
    type: string
    description: Additional metadata on the source of the tag
    enum:
    - creator
    - tag
    - exercise
    - equipment
    - sport
  EquipmentType:
    type: string
    enum:
    - weight
    - band
  SourceType:
    type: string
    enum:
    - youtube
    - unknown
