import re


class YTConsts:
    ignore_tags = {
        "#stayhome",
        "#withme",
        "10 min",
        "10 minute",
        "10min",
        "11 minute ab workout",
        "14 day",
        "2 week",
        "2 week workout program",
        "20",
        "20 min",
        "20min",
        "30 min",
        "30 minute",
        "30min",
        "30min hiit",
        "40 min",
        "40min",
        "45 minute",
        "60 minute",
        "60 minute workout with dumbbells",
        "activation",
        "and",
        "arm slimming",
        "arm toning without weights",
        "back fat workout",
        "bat wings workout",
        "be more flexible",
        "body",
        "bodyweight booty workout",
        "bootcamp workout",
        "build a butt",
        "build lean muscle",
        "build muscle and burn fat",
        "build strength workout",
        "burn fat",
        "but",
        "challenge",
        "chizzled back",
        "chizzled chest",
        "conditioning",
        "condo workout",
        "corona workout",
        "day",
        "day 3",
        "dumbbell  for",
        "fat",
        "fat burning",
        "fit",
        "fitness",
        "fitness challenge",
        "flat abs",
        "for",
        "for relaxation",
        "for sore muscles",
        "for women",
        "free workout program",
        "free workouts",
        "from home",
        "full",
        "full length hiit workout",
        "full length workout",
        "full length workout video",
        "get abs",
        "get fit from home",
        "get lean workout",
        "get shredded",
        "get stronger",
        "get toned",
        "get toned arms",
        "heather robertson fierce",
        "heather robinson",
        "heatherrobertson fierce",
        "high",
        "hit",
        "hitt",
        "home",
        "home workout",
        "how to glow up",
        "hr12week 2.0 day 8",
        "improve flexibility",
        "increase metabolism",
        "ing",
        "inner and outer thigh slimming workout",
        "intense workout",
        "intensity",
        "lean and strong",
        "leg slimming workout",
        "living room workout",
        "long and lean",
        "long lean body workout",
        "lose",
        "lower body  no weights",
        "metabolism boosting",
        "no gym workout",
        "no gym workout at home",
        "no repeet",
        "no repeets",
        "no talking",
        "no talking workout",
        "noise",
        "quarantine workout",
        "quick daily workout",
        "quick workout",
        "quiet",
        "real time workout",
        "relaxing",
        "round booty",
        "rounder butt",
        "routine",
        "routines",
        "series",
        "sholder",
        "six pack workout",
        "slim arms",
        "slim legs workout",
        "slimming",
        "stay home workout",
        "tabata for beginners",
        "thin arms",
        "thin legs workout",
        "thinner legs workout",
        "tight hips",
        "tighten skin workout",
        "tiny waist round butt",
        "weight loss workout",
        "with",
        "with me",
        "wokrout",
        "women",
        "workout at home",
        "workout for 10 minutes",
        "workout for 10 minutes a day",
        "workout for building strength",
        "workout for legs",
        "workout for people who get bored",
        "workout for weight loss",
        "workout from anywhere",
        "workout from home",
        "workout video",
        "workouts for weight loss",
        "workouts for women",
    }

    strip_words = {
        " for strength",
        "11 line",
        "at home",
        "best",
        "brutal",
        "burn",
        "circuit",
        "exercise",
        "exercises",
        "exercises for",
        "fat burning",
        "flat",
        "follow along",
        "for women",
        "from home",
        "heather robinson",
        "hitt",
        "home workout with",
        "lean",
        "only",
        "post",
        "program",
        "quick",
        "sculpted",
        "sculpting",
        "shred",
        "strenth",
        "strong",
        "tighh",
        "tight",
        "tighten",
        "toned",
        "toning",
        "training",
        "workout",
        "workout a day",
        "workout challenge",
        "workout program",
        "workouts",
        "wrkout",
    }

    possible_tags = {
        "abs",
        "arms",
        "biceps",
        "booty",
        "cardio",
        "chest",
        "core",
        "delts",
        "dumbbells",
        "full body",
        "glutes",
        "hiit",
        "legs",
        "low impact",
        "lower body",
        "mini-band",
        "no equipment",
        "no jumping",
        "shoulders",
        "strength",
        "tabata",
        "total body",
        "triceps",
        "upper body",
        "weights",
    }

    expands = {
        "abs and booty": {"butt", "abs"},
        "arm and ab": {"arms", "abs"},
        "arms and abs": {"arms", "abs"},
        "chest and back": {"chest", "back"},
        "chest triceps and shoulder": {"chest", "shoulder", "triceps"},
        "dumbbell supersets": {"weights", "supersets"},
        "full body hiit": {"hiit", "full body"},
        "full body stretch": {"stretching", "full body"},
        "legs and glutes": {"glutes", "legs"},
        "low impact cardio": {"cardio", "low impact"},
        "no repeat   weights": {"no repeats", "weights"},
        "no repeat hiit": {"hiit", "no repeats"},
        "pilates hiit": {"hiit", "pilates"},
        "strength with dumbells": {"strength", "weights"},
        "strength and cardio": {"strength", "cardio"},
        "tabata cardio": {"tabata", "cardio"},
        "total body   dumbbells": {"weights", "full body"},
        "total body dumbbell": {"weights", "full body"},
        "total body hiit": {"hiit", "full body"},
        "total body strength": {"strength", "full body"},
        "upper body strength": {"strength", "upper body"},
        "upper body superset": {"upper body", "supersets"},
    }

    dedupes = {
        "10 minute total body workout": "full body",
        "40s work +20s rest": "40s work + 20s rest",
        "ab": "abs",
        "apartment friendly": "no jumping",
        "arm": "arms",
        "band": "mini-band",
        "bicep": "biceps",
        "body weight": "no equipment",
        "body-weight": "no equipment",
        "body-weighted": "no equipment",
        "bodyweight": "no equipment",
        "bootie": "butt",
        "booty": "butt",
        "booty  with band": "mini-band",
        "bum": "butt",
        "compound": "metcon",
        "dumbbell": "weights",
        "dumbbells": "weights",
        "dumbell": "weights",
        "dumbells": "weights",
        "entire body": "full body",
        "flute": "butt",
        "for entire body": "full body",
        "for people who get bored": "no repeats",
        "glow up challenge": "glow up",
        "glute": "glutes",
        "glutes": "butt",
        "guided stretch": "stretching",
        "hip stretches": "hip stretch",
        "hips stretch": "hip stretch",
        "knee safe": "knee friendly",
        "leg": "legs",
        "leg day": "legs",
        "metabolic": "metcon",
        "metabolic conditioning": "metcon",
        "metcan": "metcon",
        "mini band": "mini-band",
        "no dumbbells": "no equipment",
        "no equiment": "no equipment",
        "no repeat": "no repeats",
        "no repetitive": "no repeats",
        "no squats no lunges": "knee friendly",
        "no weight": "no equipment",
        "no weights": "no equipment",
        "no weights glute": "no equipment",
        "non repetative": "no repeats",
        "non repetitive": "no repeats",
        "post  stretch": "stretching",
        "recovery stretch": "stretching",
        "sholders": "shoulders",
        "shoulders": "shoulder",
        "stregnth": "strength",
        "strenght": "strength",
        "strenth": "strength",
        "stretch": "stretching",
        "stretch for hips": "hip stretch",
        "stretch for relaxation": "stretching",
        "stretch for sore muscles": "stretching",
        "stretches": "stretching",
        "stretches for hips": "hip stretch",
        "stretching routine": "stretching",
        "super set": "supersets",
        "super sets": "supersets",
        "superset": "supersets",
        "tabatta": "tabata",
        "tabbata": "tabata",
        "that doesn't repeat": "no repeats",
        "total body": "full body",
        "tricep": "triceps",
        "uper body": "upper body",
        "weight": "weights",
        "without equipment": "no equipment",
        "without weights": "no equipment",
    }

    mappings = {
        "triceps": "upper body",
        "biceps": "upper body",
        "delts": "upper body",
        "back": "upper body",
        "chest": "upper body",
        "shoulder": "upper body",
        "arms": "upper body",
        "abs": "core",
        "glutes": "butt",
        "legs": "lower body",
        "quads": "lower body",
        "hamstrings": "lower body",
        "thighs": "lower body",
    }

    exercise_plurals = {
        "push up",
        "raise",
        "fly",
        "row",
        "extension",
        "back",
        "sit",
        "swimmer",
        "kickback",
        "swing",
        "deadlift",
        "pull over",
        "jack",
        "lunge",
        "pump",
        "climber",
        "drop",
        "leg lift",
        "squat",
        "hop",
        "skull crusher",
        "speed skater",
        "swimmer",
        "burpee",
        "curl",
        "drop",
        "bridge pulse",
        "sprint",
        "plank tap",
    }

    exercises_strip = {
        "cardio burst:",
    }

    exercise_dupes = {
        "kick back": "kickbacks",
        "kick backs": "kickbacks",
        "burn out": "burnout",
        "hi-low swing": "hi-lo swing",
        "knee drives": "knee driver",
        "knee drive": "knee driver",
        "lay down": "laydown",
        "100's": "100",
        "kick thru": "kick-thru",
        "sit up": "sit-up",
        "wood chop": "wood chopper",
        "woodchopper": "wood chopper",
        "l raises": "l-raises",
        "v lift": "v-lift",
        "burpees clap": "burpees + clap",
        "curls press + twist": "curls, press + twist",
        "curtsey lunges": "curtsey",
        "negative curls": "negative bicep curls",
        "scissor squats hops": "scissor squats + hops",
        "squat curl + hop": "squats, curls + hops",
        "squat curl + press": "squats, curls + press",
    }

    id_regex = re.compile(
        "^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/|shorts\/)|(?:(?:watch)?\?v(?:i)?=|\&v(?:i)?=))([^#\&\?]*).*"
    )

    chapters_regex = re.compile("(\d{0,2}:?\d{1,2}:\d{2})(.+)")
